import { Platform, StyleSheet } from "react-native";

import { colors } from "./theme";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "web" ? 32 : 12,
    paddingBottom: 32,
    gap: 20,
  },
  containerWide: {
    width: "100%",
    maxWidth: 860,
    alignSelf: "center",
  },
  header: {
    paddingHorizontal: 4,
    paddingTop: 4,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  headerIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 999,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerIconImage: {
    width: "100%",
    height: "100%",
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 9,
  },
  headerTitle: {
    fontSize: 25,
    lineHeight: 31,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: -0.3,
  },
  headerTitleMeta: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "700",
    color: colors.inkSoft,
  },
  headerAccentBar: {
    height: 4,
    width: 56,
    borderRadius: 999,
    overflow: "hidden",
  },
  headerInfoButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerInfoButtonPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  headerInfoButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.ink,
  },
  segmentedControl: {
    flexDirection: "row",
    backgroundColor: colors.surfaceMuted,
    borderRadius: 20,
    padding: 6,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  segmentButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 13,
    borderRadius: 15,
  },
  segmentButtonActive: {
    backgroundColor: colors.ink,
  },
  segmentButtonPressed: {
    backgroundColor: colors.border,
  },
  segmentButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.inkSoft,
  },
  segmentButtonTextActive: {
    color: colors.onInk,
  },
  controlsPlaceholder: {
    height: 60,
  },
  surfaceCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    gap: 18,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.07,
    shadowRadius: 28,
    elevation: 2,
  },
  aboutModalSafeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  aboutModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 860,
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
    gap: 12,
  },
  aboutModalTitle: {
    flex: 1,
    fontSize: 22,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: -0.2,
  },
  aboutModalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  aboutModalCloseButtonPressed: {
    backgroundColor: colors.border,
  },
  aboutModalContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 36,
  },
  aboutModalBody: {
    width: "100%",
  },
  aboutModalBodyWide: {
    maxWidth: 860,
    alignSelf: "center",
  },
  infoCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 22,
    gap: 18,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.06,
    shadowRadius: 26,
    elevation: 2,
  },
  infoCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  infoCardIcon: {
    width: 76,
    height: 76,
    borderRadius: 999,
  },
  infoCardTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  infoEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    color: colors.inkFaint,
    textTransform: "uppercase",
  },
  infoTitle: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: "800",
    color: colors.ink,
  },
  infoDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.inkSoft,
  },
  infoLinkList: {
    gap: 10,
    paddingTop: 4,
  },
  infoLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 20,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoLinkRowPressed: {
    backgroundColor: colors.border,
  },
  infoLinkIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoLinkTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  infoLinkLabel: {
    fontSize: 11.5,
    fontWeight: "800",
    color: colors.inkFaint,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  infoLinkValue: {
    fontSize: 14.5,
    lineHeight: 21,
    fontWeight: "800",
    color: colors.ink,
  },
  dateCard: {
    gap: 18,
  },
  dateNavRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  dateNavCenter: {
    flex: 1,
    alignItems: "center",
  },
  dateValue: {
    fontSize: 21,
    fontWeight: "800",
    color: colors.ink,
    textAlign: "center",
    letterSpacing: -0.2,
  },
  weekNavButton: {
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  weekNavButtonPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  weekNavButtonDisabled: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
  },
  todayShortcutRow: {
    alignItems: "flex-end",
  },
  todayShortcutButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: colors.mintTint,
    borderWidth: 1,
    borderColor: "#C9E9E2",
  },
  todayShortcutButtonPressed: {
    backgroundColor: "#CDEAE3",
  },
  todayShortcutText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.mintDark,
  },
  weekRow: {
    flexDirection: "row",
    gap: 8,
  },
  dayChip: {
    flex: 1,
    minWidth: 0,
    minHeight: 76,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.border,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  dayChipToday: {
    backgroundColor: colors.mintTint,
    borderColor: colors.mint,
  },
  dayChipActive: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  dayChipPressed: {
    backgroundColor: "#F1E9D8",
  },
  dayChipDisabled: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    opacity: 0.5,
  },
  dayChipWeekday: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.inkSoft,
  },
  dayChipSunday: {
    color: colors.sunday,
  },
  dayChipSaturday: {
    color: colors.saturday,
  },
  dayChipDate: {
    fontSize: 19,
    fontWeight: "800",
    color: colors.ink,
  },
  dayChipWeekdayDisabled: {
    color: colors.inkFaint,
  },
  dayChipDateDisabled: {
    color: colors.inkFaint,
  },
  dayChipTextActive: {
    color: colors.onInk,
  },
  todayDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.mint,
    marginTop: 2,
  },
  todayDotActive: {
    backgroundColor: "rgba(251, 246, 236, 0.85)",
  },
  dateLimitNotice: {
    fontSize: 12.5,
    fontWeight: "700",
    color: colors.inkFaint,
    textAlign: "right",
    lineHeight: 18,
  },
  feedbackCard: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    padding: 28,
    borderRadius: 24,
    backgroundColor: colors.surfaceMuted,
  },
  feedbackText: {
    fontSize: 14.5,
    color: colors.inkSoft,
  },
  errorIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.pinkTint,
  },
  errorTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.ink,
    textAlign: "center",
  },
  errorText: {
    fontSize: 14.5,
    lineHeight: 21,
    color: colors.inkSoft,
    textAlign: "center",
  },
  menuGrid: {
    gap: 14,
  },
  menuGridWide: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  mealCardWrap: {
    width: "100%",
  },
  mealCardWrapWide: {
    flex: 1,
  },
  mealCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 14,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 1,
  },
  mealCardStretch: {
    height: "100%",
  },
  mealHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  mealIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  mealHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  mealLabel: {
    fontSize: 16.5,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: -0.1,
  },
  mealMeta: {
    fontSize: 12.5,
    fontWeight: "700",
    color: colors.inkSoft,
  },
  menuItemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  menuBullet: {
    width: 6,
    height: 6,
    borderRadius: 999,
    marginTop: 8,
  },
  menuItemText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 23,
    color: colors.ink,
  },
  emptyMealCard: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 22,
    backgroundColor: colors.surfaceMuted,
    alignItems: "center",
    gap: 8,
  },
  emptyMealText: {
    fontSize: 13.5,
    color: colors.inkSoft,
    textAlign: "center",
  },
});
